version: '3'
services:
  # Server
  api:
    build: .
    ports:
      - '13000:5858'
      - '3000:3000'
    expose:
      - 3000
      - 5858
    tty: true
    volumes:
      - './dist:/node/app/dist'
    environment:
      - NODE_ENV=docker-local
    container_name: api
    depends_on:
      - db
#    networks:
#      - default

  # PostgreSQL
  db:
    image: postgres:13-alpine
    ports:
      - '5432:5432'
    expose:
      - 5432
    environment:
      POSTGRES_USER: chewbacca
      POSTGRES_PASSWORD: rawr
      POSTGRES_DB: web3data
    container_name: web3data-db
#    networks:
#      - default

#networks:
#  default:
#    external:
#      name: transaction-syncing-service_default
